//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace br.com.maplink.calculorota.console.CalculoRotaWcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosEntrada", Namespace="http://www.maplink.com.br/caculorota/v1")]
    [System.SerializableAttribute()]
    public partial struct DadosEntrada : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cep {
            get {
                return this.CepField;
            }
            set {
                if ((object.ReferenceEquals(this.CepField, value) != true)) {
                    this.CepField = value;
                    this.RaisePropertyChanged("Cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rua {
            get {
                return this.RuaField;
            }
            set {
                if ((object.ReferenceEquals(this.RuaField, value) != true)) {
                    this.RuaField = value;
                    this.RaisePropertyChanged("Rua");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoCalculo", Namespace="http://www.maplink.com.br/caculorota/v1")]
    [System.SerializableAttribute()]
    public partial class ResultadoCalculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CustoTotalCombustivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CustoTotalPedagioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DistanciaTotalRotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan TempoTotalRotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CustoTotalCombustivel {
            get {
                return this.CustoTotalCombustivelField;
            }
            set {
                if ((this.CustoTotalCombustivelField.Equals(value) != true)) {
                    this.CustoTotalCombustivelField = value;
                    this.RaisePropertyChanged("CustoTotalCombustivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CustoTotalPedagio {
            get {
                return this.CustoTotalPedagioField;
            }
            set {
                if ((this.CustoTotalPedagioField.Equals(value) != true)) {
                    this.CustoTotalPedagioField = value;
                    this.RaisePropertyChanged("CustoTotalPedagio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DistanciaTotalRota {
            get {
                return this.DistanciaTotalRotaField;
            }
            set {
                if ((this.DistanciaTotalRotaField.Equals(value) != true)) {
                    this.DistanciaTotalRotaField = value;
                    this.RaisePropertyChanged("DistanciaTotalRota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TempoTotalRota {
            get {
                return this.TempoTotalRotaField;
            }
            set {
                if ((this.TempoTotalRotaField.Equals(value) != true)) {
                    this.TempoTotalRotaField = value;
                    this.RaisePropertyChanged("TempoTotalRota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcfServiceFault", Namespace="http://schemas.datacontract.org/2004/07/br.com.maplink.calculorota.common.wcf")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(br.com.maplink.calculorota.console.CalculoRotaWcf.WcfCalculoRotaFault))]
    public partial class WcfServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Target {
            get {
                return this.TargetField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetField, value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcfCalculoRotaFault", Namespace="http://schemas.datacontract.org/2004/07/br.com.maplink.calculorota.common.wcf")]
    [System.SerializableAttribute()]
    public partial class WcfCalculoRotaFault : br.com.maplink.calculorota.console.CalculoRotaWcf.WcfServiceFault {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.maplink.com.br/caculorota/v1", ConfigurationName="CalculoRotaWcf.ICalculoRota")]
    public interface ICalculoRota {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.maplink.com.br/caculorota/v1/ICalculoRota/CalcularRotaMaisRapida", ReplyAction="http://www.maplink.com.br/caculorota/v1/ICalculoRota/CalcularRotaMaisRapidaRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(br.com.maplink.calculorota.console.CalculoRotaWcf.WcfCalculoRotaFault), Action="http://www.maplink.com.br/caculorota/v1/ICalculoRota/CalcularRotaMaisRapidaWcfCal" +
            "culoRotaFaultFault", Name="WcfCalculoRotaFault", Namespace="http://schemas.datacontract.org/2004/07/br.com.maplink.calculorota.common.wcf")]
        br.com.maplink.calculorota.console.CalculoRotaWcf.ResultadoCalculo CalcularRotaMaisRapida(br.com.maplink.calculorota.console.CalculoRotaWcf.DadosEntrada[] entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.maplink.com.br/caculorota/v1/ICalculoRota/CalcularRotaEvitandoTransito" +
            "", ReplyAction="http://www.maplink.com.br/caculorota/v1/ICalculoRota/CalcularRotaEvitandoTransito" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(br.com.maplink.calculorota.console.CalculoRotaWcf.WcfCalculoRotaFault), Action="http://www.maplink.com.br/caculorota/v1/ICalculoRota/CalcularRotaEvitandoTransito" +
            "WcfCalculoRotaFaultFault", Name="WcfCalculoRotaFault", Namespace="http://schemas.datacontract.org/2004/07/br.com.maplink.calculorota.common.wcf")]
        br.com.maplink.calculorota.console.CalculoRotaWcf.ResultadoCalculo CalcularRotaEvitandoTransito(br.com.maplink.calculorota.console.CalculoRotaWcf.DadosEntrada[] entrada);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculoRotaChannel : br.com.maplink.calculorota.console.CalculoRotaWcf.ICalculoRota, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculoRotaClient : System.ServiceModel.ClientBase<br.com.maplink.calculorota.console.CalculoRotaWcf.ICalculoRota>, br.com.maplink.calculorota.console.CalculoRotaWcf.ICalculoRota {
        
        public CalculoRotaClient() {
        }
        
        public CalculoRotaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculoRotaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculoRotaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculoRotaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public br.com.maplink.calculorota.console.CalculoRotaWcf.ResultadoCalculo CalcularRotaMaisRapida(br.com.maplink.calculorota.console.CalculoRotaWcf.DadosEntrada[] entrada) {
            return base.Channel.CalcularRotaMaisRapida(entrada);
        }
        
        public br.com.maplink.calculorota.console.CalculoRotaWcf.ResultadoCalculo CalcularRotaEvitandoTransito(br.com.maplink.calculorota.console.CalculoRotaWcf.DadosEntrada[] entrada) {
            return base.Channel.CalcularRotaEvitandoTransito(entrada);
        }
    }
}
